name: Update China Domain File

on:
  schedule:
    - cron: '0 23 * * *'  # 每分钟运行一次

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Download file from URL
      run: wget -O accelerated-domains.china.conf https://testingcf.jsdelivr.net/gh/felixonmars/dnsmasq-china-list@master/accelerated-domains.china.conf

    - name: Append Custome White List to accelerated-domains.china.conf
      run: cat Others/ChinaDomain/CustomeWhite.list >> accelerated-domains.china.conf

    - name: Overwrite final_config.list in repo
      run: cp accelerated-domains.china.conf Others/ChinaDomain/ChinaDomainFinal.list

    - name: Commit and push
      run: |
        git_status=$(git status --porcelain)
        if [[ -n "$git_status" ]]; then
          git add Others/ChinaDomain/ChinaDomainFinal.list
          git commit -m "Update final_config.list"
          echo "File Has Updated"
        else
          echo "Nothing changed"
          exit 1
        fi

    - name: Push changes
      uses: ad-m/github-push-action@master
      if: success()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
